# -*- coding: utf-8 -*-
"""NumPy-kutubxonasi-yakuniy amaliyot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMRDutqadQhecgJ-pjEDsZdPEqXQCigF

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.

`💡Ishora` import … as` and `np.__version__, np.show_config
"""

import numpy as np

np.version

np.show_config

"""#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array
"""

arr = np.array([1, 2, 3, 4, 5])

"""#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---



"""

arr1 = np.zeros(9)
arr1

"""`💡Ishora` np.zeros"""

arr1.size

"""#### 4. Massiv yarating va uning xotira hajmini toping.

`💡Ishora` size, itemsize
"""

arr2 = np.arange(20)

arr2.itemsize

"""#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?

`💡Ishora` np.info
"""

np.info(np.add)

"""#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.

`💡Ishora` array[12]
"""

arr3 = np.zeros(12)
arr3[5] = 1
arr3

"""#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.

`💡Ishora` arange
"""

arr4 = np.arange(20, 60)
arr4



"""#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)

`💡Ishora` array[::-1]
"""

revr_arr4 = np.sort(-arr4)
revr_arr4

"""#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.

`💡Ishora` reshape
"""

arr5 = np.arange(12, 21).reshape(3, 3)
arr5

"""#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]

`💡Ishora` np.nonzero
"""

a = np.array([3, 7, 0, 0, 9, 0])
b = np.nonzero(a)
print(b)

"""#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.

`💡Ishora` np.random.random
"""

arr6 = np.random.random((2, 2, 2))
arr6

"""#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.

`💡Ishora` min, max
"""

arr7 = np.random.random((9, 9))
arr7

np.min(arr7)

np.max(arr7)

"""#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```

`💡Ishora` NaN = not a number, inf = infinity
"""

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

"""#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.

`💡Ishora` np.dot` or `np.ones
"""

x = np.random.randint(1, 10, (6, 3))
x

y = np.random.randint(1, 10, (3, 4))
y

np.dot(x, y)

"""#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```
"""

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

"""#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```
"""

A = np.array([1, 2])
B = np.array([4, 5])

np.where(A>B, True, False)

np.where(A<B,True, False)

np.where(A<=B, True, False)

"""#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

none

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.

`💡Ishora` np.intersect1d
"""

arr1 = np.array([1, 2, 4, 5])
arr2 = np.array([3, 4, 5, 7])
result = np.intersect1d(arr1, arr2)
result

"""#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc
"""

arr = np.random.randn(10)
arr

np.floor(arr)

arr.astype(int)

np.trunc(arr)

butun_qism = arr -(arr%1)
butun_qism

"""#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.

`💡Ishora` np.arange
"""

a = np.tile(np.arange(3), (3, 1))
a

"""#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.

`💡Ishora` sort
"""

arr = np.random.random(10)
arr

np.sort(arr)

"""#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal
"""

a = np.random.randint(1, 10, (3, 3))
a

b = np.random.randint(1, 10, (3, 3))
b

np.array_equal(a, b)

A = np.zeros(5)
A

B = np.zeros(5)
B

np.array_equal(A,B)

"""#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.

`💡Ishora` np.dot or np.ones
"""

x = np.random.randint(2, 20, (6, 3))
x

y = np.random.randint(1, 10, (3, 4))
y

np.dot(x, y)

"""#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.

`💡Ishora` argmax
"""

c = np.random.random(5)
c

c[c.argmax()] = 0
c

"""#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.

`💡Ishora` np.datetime64, np.timedelta64
"""

today = np.datetime64('today','D')
print("Bugun:", today)

# Kecha
yesterday = today - np.timedelta64(2, 'D')
print("Kecha:", yesterday)

# Ertaga
tomorrow = today + np.timedelta64(1, 'D')
print("Ertaga:", tomorrow)

"""#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.

`💡Ishora` np.arange(dtype=datetime64['D'])
"""

# 2016 yil yanvar oyining boshlanishi va oxiri
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')  # Fevral 1 kiritiladi, chunki aralashda oxirgi sana olinmaydi

# Sanalar oralig'ini yaratish
dates = np.arange(start_date, end_date, dtype='datetime64[D]')
print(dates)

"""#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc`
"""

arr = np.random.randn(10)
arr

np.floor(arr)



arr.astype(int)

np.trunc(arr)

butun_qism = arr -(arr%1)
butun_qism

"""#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.

`💡Ishora` np.add.reduce
"""

arr11 = np.random.randint(1, 100, size=10)
arr11

np.sum(arr11)

np.add.reduce(arr11)

"""#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.

`💡Ishora` array[::4]
"""

v = np.arange(6)
v

# Har bir element orasiga 3 ta nol qo'shish
# Yangi uzunlik: har bir element + 3 ta nol, lekin oxirida nol kerak emas
n = 3  # qo'shiladigan nol soni
new_length = len(v) + (len(v) - 1) * n

# Natija uchun bo'sh array yaratish
result = np.zeros(new_length, dtype=int)

# Elementlarni joylash
result[::n+1] = v

print(result)

"""#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided
"""

a = np.arange(1, 15)
a

# Har bir oynani yaratish (window size = 4)
window_size = 4
b = np.array([a[i:i+window_size] for i in range(len(a) - window_size + 1)])

print(b)

"""#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.

`💡Ishora` np.bincount, argmax
"""

d = np.array([1, 1, 5 , 6, 4, 5, 7, 7])

np.unique(d)

counts = np.bincount(d)
counts

# np.bincount - har bir butun son nechta borligini hisoblaydi
counts = np.bincount(d)

# Eng ko'p takrorlangan qiymatni topish
most_frequent = counts.argmax()
print("Eng ko'p uchraydigan qiymat:", most_frequent)

# Agar barcha takrorlangan qiymatlarni topmoqchi bo'lsak:
duplicates = np.where(counts > 1)[0]
print("Takrorlangan qiymatlar:", duplicates)

"""#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`

none
"""